// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqykvexnmzwskzoqizzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxeWt2ZXhubXp3c2t6b3FpenpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDg0MTAsImV4cCI6MjA3MjMyNDQxMH0.5LuCYbaEIZr8P_XS8oEoz44f96Iw-x8VSPqZDHKRdEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});